apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: cloudbees.event.head_commit.modified.endsWith('.yaml')
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo "${{ cloudbees.run_id }}"
          echo "${{ job.id }}"
          echo "${{ step.internal.id }}"
          echo "${{ cloudbees.api.url }}"
          echo "${{ cloudbees.api.token }}"
          echo "${{ cloudbees.version }}"
          echo "${{ cloudbees.event.after }}"


      - name: Dump GitHub context
        uses: docker://cgr.dev/chainguard/wolfi-base:latest
        env:
          CLOUDBEES_CONTEXT: ${{ toJSON(cloudbees) }}
        run: |
          echo "----- CONTEXT ------"
          echo "cloudbees.scm.sha: ${{ cloudbees.scm.sha }}"
          echo "$CLOUDBEES_CONTEXT"

      - name: Run Python
        uses: docker://dvcorg/cml-py3:latest
        env:
          CLOUDBEES_OUTPUTS: ${{ cloudbees.workspace }}/outputs
        run: |
           pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests fsspec s3fs tabulate
           python check.py
        
          
      - name: Copy files to gcs
        uses: ps-ssingh/gcs-action@v1.2
        with:
          application_credentials: ${{ secrets.GCP_AUTH }}
          project_id: ps-ssingh-gcp
          command: lifecycle
          destination_file: gs://saas-pssingh/
          lifecycle_config_file: lifecycle.json


  job-second:
      steps:
        - name: Checkout
          uses: cloudbees-io/checkout@v1
      
        - name: Say hello
          uses: docker://golang:1.20.3-alpine3.17
          shell: sh
          run: |
            echo "hello world"
            echo "${{ cloudbees.run_id }}"
            echo "${{ job.id }}"
            echo "${{ step.internal.id }}"
            echo "${{ cloudbees.api.url }}"
            echo "${{ cloudbees.api.token }}"
            echo "${{ cloudbees.version }}"
            echo "${{ cloudbees.event.after }}"

        - name: Dump GitHub context
          uses: docker://cgr.dev/chainguard/wolfi-base:latest
          env:
            CLOUDBEES_CONTEXT: ${{ toJSON(cloudbees) }}
          run: |
            echo "----- CONTEXT ------"
            echo "cloudbees.scm.sha: ${{ cloudbees.scm.sha }}"
            echo "$CLOUDBEES_CONTEXT"