apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          
      - name: Copy files to gcs
        uses: ps-ssingh/gcs-action@v1.0
        with:
          application_credentials: ${{ secrets.GCP_AUTH }}
          project_id: ps-ssingh-gcp
          command: lifecycle
          lifecycle_config_file: lifecycle.json
