apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

  filechanged: 
    needs: checkout   
    steps:
      - name: Check file context
        uses: docker://alpine/git:latest
        env:
            CLOUDBEES_CONTEXT: ${{ toJSON(cloudbees) }}
        run: |
            echo $(git show --name-only --oneline HEAD)
  
  build:
    needs: filechanged
    if: ${{cloudbees.event.head_commit.modified[0] == 'pythonFiles/newFile.py' || cloudbees.event.head_commit.modified[0] == 'pythonFiles/test.py'  }}
    steps:  
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo "${{ cloudbees.run_id }}"
          echo "${{ job.id }}"
          echo "${{ step.internal.id }}"
          echo "${{ cloudbees.api.url }}"
          echo "${{ cloudbees.api.token }}"
          echo "${{ cloudbees.version }}"
          echo "${{ cloudbees.event.after }}"
          echo "${{cloudbees.event.head_commit.modified[0]}}"


      - name: Dump GitHub context
        uses: docker://cgr.dev/chainguard/wolfi-base:latest
        env:
          CLOUDBEES_CONTEXT: ${{ toJSON(cloudbees) }}
        run: |
          echo "----- CONTEXT ------"
          echo "cloudbees.scm.sha: ${{ cloudbees.scm.sha }}"
          echo "$CLOUDBEES_CONTEXT"

      - name: Run Python
        uses: docker://dvcorg/cml-py3:latest
        env:
          CLOUDBEES_OUTPUTS: ${{ cloudbees.workspace }}/outputs
        run: |
           pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests fsspec s3fs tabulate
        
          
      - name: Copy files to gcs
        uses: ps-ssingh/gcs-action@v1.2
        with:
          application_credentials: ${{ secrets.GCP_AUTH }}
          project_id: ps-ssingh-gcp
          command: lifecycle
          destination_file: gs://saas-pssingh/
          lifecycle_config_file: lifecycle.json


  job-second:
      if: ${{cloudbees.event.head_commit.modified[0] == 'random/new.txt' || cloudbees.event.head_commit.modified[0] == 'random/new2.txt'||cloudbees.event.head_commit.modified[0] == 'random/newdir/first.txt'}}
      needs: filechanged
      steps:
        - name: Checkout
          uses: cloudbees-io/checkout@v1
      
        - name: Say hello
          uses: docker://golang:1.20.3-alpine3.17
          shell: sh
          run: |
            echo "hello world"
            echo "${{ cloudbees.run_id }}"
            echo "${{ job.id }}"
            echo "${{ step.internal.id }}"
            echo "${{ cloudbees.api.url }}"
            echo "${{ cloudbees.api.token }}"
            echo "${{ cloudbees.version }}"
            echo "${{ cloudbees.event.after }}"
        - name: Check file context
          uses: docker://alpine/git:latest
          env:
            CLOUDBEES_CONTEXT: ${{ toJSON(cloudbees) }}
          run: |
            echo $(git show --name-only --oneline HEAD)
        - name: Dump GitHub context
          uses: docker://cgr.dev/chainguard/wolfi-base:latest
          env:
            CLOUDBEES_CONTEXT: ${{ toJSON(cloudbees) }}
          run: |
            echo "----- CONTEXT ------"
            echo "cloudbees.scm.sha: ${{ cloudbees.scm.sha }}"
            echo "$CLOUDBEES_CONTEXT"
